name : Automate Workflow and Docker release 

on:
  push:
    branches:
      - main
    paths:
      - "Projectss"

env:
  GITHUB_USERNAME: ${{github.actor}}
  GITHUB_PASSWORD: ${{secrets.REGISTRY_ACCESS_TOKEN}}
  REGISTRY: ghcr.io 
  IMAGE_NAME: kushalsubedi/flask-app
jobs:
  build_docker_image:
    runs-on: ubuntu-latest 

  steps:
    - name: Checkout repository 
      uses: action/Checkout@v4 

    - name: Login to Ghcr
      uses: docker/login-action@v3
      with:
        registry: ${{env.Registry }}
        username: ${{env.GITHUB_USERNAME}}
        password: ${{env.GITHUB_PASSWORD}}
    - name: Build docker image 
      uses: docker/build-push-action@v5 
      with:
        context: ./Projects
        push: true 
        tags: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest 



